In [1]:
class Category:
  BOOKS = "BOOKS"
  CLOTHING = "CLOTHING"

train_x = "I love the book", "this is a great book", "the fit is great", "I love the shoes"
train_y = [Category.BOOKS, Category.BOOKS, Category.CLOTHING, Category.CLOTHING]

In [2]:
!pip install spacy
!python -m spacy download en_core_web_md

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.5/33.5 MB 59.4 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_md')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [3]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(binary=True, ngram_range=(1,2))
train_x_vectors = vectorizer.fit_transform(train_x)

print(vectorizer.get_feature_names_out())

print(train_x_vectors.toarray())

['book' 'fit' 'fit is' 'great' 'great book' 'is' 'is great' 'love'
 'love the' 'shoes' 'the' 'the book' 'the fit' 'the shoes' 'this'
 'this is']
[[1 0 0 0 0 0 0 1 1 0 1 1 0 0 0 0]
 [1 0 0 1 1 1 1 0 0 0 0 0 0 0 1 1]
 [0 1 1 1 0 1 1 0 0 0 1 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 1 0 0 1 0 0]]


In [4]:
from sklearn import svm

clf = svm.SVC(kernel='linear')
clf.fit(train_x_vectors, train_y)

SVC(kernel='linear')

In [5]:
test_x = vectorizer.transform(['I like the book'])

clf.predict(test_x)

array(['BOOKS'], dtype='<U8')

## Word Vectors

In [6]:
import spacy

nlp = spacy.load("en_core_web_md")

In [7]:
docs = [nlp(text) for text in train_x]
#print(docs[0].vector)
train_x_word_vectors = [x.vector for x in docs]

In [8]:
clf_svm_wv = svm.SVC(kernel='linear')
clf_svm_wv.fit(train_x_word_vectors, train_y)

SVC(kernel='linear')

In [9]:
test_x = ["these earrings hurt"]
test_x_docs = [nlp(text) for text in test_x]
test_x_word_vectors = [x.vector for x in test_x_docs]

clf_svm_wv.predict(test_x_word_vectors)

array(['CLOTHING'], dtype='<U8')

In [10]:
import re
regexp = re.compile(r"^ab[^\s]*cd$")

phrases = ["I liked that history", ""]

matches = []
for phrase in phrases:
  if re.match(regexp, phrase):
    matches.append(phrase)

print(matches)

[]


In [11]:
import nltk

nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [12]:
#import nltk
nltk.download('punkt_tab')
from nltk import punkt
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

phrase = "reading the books."
words = word_tokenize(phrase)
print(words)

stemmed_words = []
for word in words:
  stemmed_words.append(stemmer.stem(word))

" ".join(stemmed_words)

['reading', 'the', 'books', '.']


[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


'read the book .'

In [13]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

phrase = "reading the books"
words = word_tokenize(phrase)

lemmatized_words = []
for word in words:
  lemmatized_words.append(lemmatizer.lemmatize(word, pos='v'))

' '.join(lemmatized_words)

'read the book'


## Stopword Removal




In [14]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
stop_words = stopwords.words('english')

phrase = "Here is an example sentence demonstrating the removal of stopwords"
words = word_tokenize(phrase)

stripped_phrase = []
for word in words:
  if word not in stop_words:
    stripped_phrase.append(word)

' '.join(stripped_phrase)

'Here example sentence demonstrating removal stopwords'

## Various other techniques (spell correction, sentiment, & pos tagging)

In [15]:
!python -m textblob.download_corpora

[nltk_data] Downloading package brown to /root/nltk_data...
[nltk_data]   Package brown is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package conll2000 to /root/nltk_data...
[nltk_data]   Package conll2000 is already up-to-date!
[nltk_data] Downloading package movie_reviews to /root/nltk_data...
[nltk_data]   Package movie_reviews is already up-to-date!
Finished.


In [16]:
from textblob import TextBlob

#phrase = "this is an example"
phrase = "I read the book"
phrase = "the book was great"
phrase = "I loved the book"
phrase = "I hated the book"
tb_phrase = TextBlob(phrase)

tb_phrase.correct()

tb_phrase.tags

tb_phrase.sentiment

Sentiment(polarity=-0.9, subjectivity=0.7)

## Transformer Architecture

In [17]:
!pip install spacy-transformers
!python -m spacy download en_core_web_trf

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 457.4/457.4 MB 1.7 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_trf')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [18]:
import spacy
import torch

nlp = spacy.load("en_core_web_trf")
doc = nlp("Here is some text to encode.")

#print(doc.tensor.shape

In [19]:
class Category:
  BOOKS = "BOOKS"
  BANK = "BANK"

train_x = ["good characters and plot progression", "check out the book", "good story. would recommend", "novel recommendation", "need to make a deposit to the bank", "balance inquiry savings", "save money"]
train_y = [Category.BOOKS, Category.BOOKS, Category.BOOKS, Category.BOOKS, Category.BANK, Category.BANK, Category.BANK]


In [23]:
from sklearn import svm
import numpy as np

docs = [nlp(text) for text in train_x]

train_x_vectors = []
for doc in docs:
    if doc.tensor.shape[0] == 0: # Check if the tensor is empty (no tokens for transformer)
        # Fallback to a zero vector if doc.tensor is empty.
        # en_core_web_trf uses a transformer model, typically BERT-base, which has 768 dimensions.
        train_x_vectors.append(np.zeros(768, dtype=np.float32))
    else:
        # Average across tokens (axis 0) and layers (axis 1) to get a single 1D vector per document
        train_x_vectors.append(doc.tensor.mean(axis=(0, 1)))

clf_svm = svm.SVC(kernel='linear')

clf_svm.fit(train_x_vectors, train_y)

test_x = ["check this story out"]
docs = [nlp(text) for text in test_x]

test_x_vectors = []
for doc in docs:
    if doc.tensor.shape[0] == 0:
        test_x_vectors.append(np.zeros(768, dtype=np.float32))
    else:
        test_x_vectors.append(doc.tensor.mean(axis=(0, 1)))

clf_svm.predict(test_x_vectors)

array(['BOOKS'], dtype='<U5')